name: Feature Request
description: Propose something new
labels: [feature]

body:
  - type: dropdown
    attributes:
      label: Area
      options: [Backend, Frontend, DevOps]
    validations:
      required: true

  - type: textarea
    attributes:
      label: What do you want to build?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this needed?
    validations:
      required: true